### ISSUE TITLE
Circlator

### ISSUE THREAD

**Issue by hoelzer** [sandraTriebel/mycoplasma_bovis_assembly#1]
Integration of a circularization tool as final step of the assembly pipeline? Does M. bovis circularize?

**Comment by hoelzer** [comment]
does flye have a circularization parameter @sandraTriebel ? Anyway, a rule for circlator would be beneficial

**Comment by sandraTriebel** [comment]
Flye, dooes not have a circularization parameter, @hoelzer .

**Comment by hoelzer** [comment]
Ok, thx. Then we can only go for another rule using circlator on the final assembly

**Comment by sandraTriebel** [comment]
Circlator takes the assembly and ONT or PacBio reads as input. Using ONT reads, some thresholds has to be scaled down (thresholds recommended as in the command for nanopore reads).
circlator all --merge_min_id 85 --merge_breaklen 1000 assembly.fasta reads output_directory

The brief instuctions of Circlator recommend a polishing after the circularization. @hoelzer, should we put Circlator at an earlier point in the pipeline (right after flye)?

**Comment by hoelzer** [comment]
Ah interesting. I am not sure. From my naive point of view, I would think that it is easier to circularize a genome when the ends of contigs are already polished, or? 

But when the authors recommend this, we can also put it directly after flye and then continue with all the polishing.

**Comment by sandraTriebel** [comment]
The long-read-only assembly as well as the long reads are more errorprone, so circularization after polishing sounds clever too.

Here the brief instructions:https://github.com/sanger-pathogens/circlator/wiki/Brief-instructions
The authors recommend a polishing w/ Quiver, or Nanopolish.

**Comment by hoelzer** [comment]
ok thx, but the instructions are from 2017 and we dont want to use Nanopolish anymore :) 

I say: let's try circlator after all of our polishing with the final assembly. And then we check if this changes anything and decide based on this how to continue.

**Comment by sandraTriebel** [comment]
Oh, that's quite a while. Thx.
But we set the thresholds as recommended for nanopore data?

> --merge_min_id 85 --merge_breaklen 1000

**Comment by hoelzer** [comment]
yeah. I would set the params like this. 

and I just remembered that in another project circlator was not working so well (and was slow), so we could also try the following:

https://github.com/Kzra/Simple-Circularise: 

````
python simple_circularise.py contig.fasta test.fasta -r 10 -min 10000
````

* -r tells the script to search for a maximum repeat overlap starting from a search of 10 nt
* -min 10000 might be reasonably adjusted to 1M because of the expected genome size

But for now, please add the circlator rule. Then we check what the output looks like. If we are not satisfied, we can try the above script manually and if it works nicer, use this.

**Comment by sandraTriebel** [comment]
So we'll see, if circlator is working well on our data.

But if we polish the assembly with short reads, the accuracy increases and so the thresholds could be higher for the circularization. Or am I wrong?

**Comment by hoelzer** [comment]
Not exactly. You are right. I mean our assembly will be more accurate, but the nanopore reads that circlator uses are still erroneous. So I think we can simply start with this parameter setup and see

**Comment by sandraTriebel** [comment]
We leaved circlator out of the pipeline, because it might take al long time and don't improve the results this much.
