### ISSUE TITLE
polishing procedure

### ISSUE THREAD

**Issue by hoelzer** [sandraTriebel/mycoplasma_bovis_assembly#11]
Please correct me if I am wrong, @sandraTriebel 

At the moment we do only polishing using the short reads? So we do not polish the flye assembly with the long reads, right? 

If so, I think we should do this, according to: 
https://achri.blogspot.com/2019/12/nanopore-bacterial-genome-assemblies.html?m=1

flye >> 4x racon >> 1x medaka

When I remember correctly, this is what you already do, just that you use the short reads, right? 

Maybe the benefit is not that high, but something like 

flye >> 4x racon w/ LR >> 1x medaka w/ LR >> 4x racon w/ SR >> 1x medaka w/ SR

would be the most accurate way. Besides, we could also test what I have written here #10 

flye >> 4x racon w/ LR >> 1x medaka w/ LR >> SPAdes w/ trusted contig option 

```
flye --nano-raw barcode06.fastq --threads 8 --iterations 2 --plasmids -g 3m --out-dir barcode06

for n in 1 2 3 4; 
do 
minimap2 racon`expr $n - 1`.fasta ../barcode06.fastq > minimap.paf; 
racon ../barcode06.fastq minimap.paf racon`expr $n - 1`.fasta -e 0.15 -t 8 -m 8 -x -6 -g -8 -w 500 > racon$n.fasta; 
done

medaka_consensus -i ../barcode06.fastq -d racon4.fasta -o medaka -t 8 
```

**Comment by sandraTriebel** [comment]
Currently, the pipeline contains:
flye  >> 4x Racon w/ LR >>1x medaka w/ LR >> 4x Racon w/ SR.

Can medaka take short reads as an input?

**Comment by hoelzer** [comment]
Ok, that's great. Dont know if medaka can take short reads honestly. I think you also tried pilon with the short reads but run into some issues?

Either way, I would Stick to What you have implemented for now, that's good.

**Comment by sandraTriebel** [comment]
Yes, there were some problems while installing Pilon.

I looked it up and I don't think medaka can take short reads, medaka is provided by ONT Research.
'medaka is a tool to create a consensus sequence from nanopore sequencing data.' (https://github.com/nanoporetech/medaka)

**Comment by hoelzer** [comment]
Ok thx, we stick to the current Implementation (with updating racon) and in
addition we can see later on What the additional spades Module with trusted
contig flag yields in comparison to simply polishing the flye assembly with
short reads using racon

sandraTriebel <notifications@github.com> schrieb am Mo., 16. Dez. 2019,
13:25:
