### ISSUE TITLE
qcat with trimming option

### ISSUE THREAD

**Issue by hoelzer** [sandraTriebel/mycoplasma_bovis_assembly#12]
@sandraTriebel are you aware that qcat also has a trimming option that we can use? 

```
conda install qcat
conda install future
cat *.fastq | qcat --trim -b demultiplexed
```

**Comment by sandraTriebel** [comment]
Yes, I've already used the --trim parameter in the qcat command.
'qcat -t {threads} -k NBD103/NBD104 --trim -f {input} -b {params.outputdir}'
