### ISSUE TITLE
Filtering long reads

### ISSUE THREAD

**Issue by hoelzer** [sandraTriebel/mycoplasma_bovis_assembly#3]
Filtlong, --min_length 1000 nt

**Comment by hoelzer** [comment]
We have two options: 

1) running filtlong simply with long reads, thus the phred quality score is used:

```
filtlong --min_length 1000 input.fastq.gz | gzip > output.fastq.gz
```

2) or we directly use the short reads: thus, the long-read phred quality score is ignored and read quality will be determined by k-mer matches between the short and long reads. (a more accurate gauge of quality) 

```
filtlong -1 illumina_1.fastq.gz -2 illumina_2.fastq.gz --min_length 1000 input.fastq.gz | gzip > output.fastq.gz
```

For the second approach, we could also do trimming (w/ ``--trim``).

@sandraTriebel please implement for now only 1), however, 2) seems very reasonable and we could also test this with the quality-checked short reads later on.

**Comment by sandraTriebel** [comment]
If we'll test Filtong w/ short reads later, maybe we have to change the --nano-raw parameter in flye to --nano-corr. But the error rate for --nano-corr should be <2%.
Is this necessary and if yes, how can we calculate the error rate of the filtered reads?

**Comment by hoelzer** [comment]
@sandraTriebel ah I agree. If we correct the LR w/ the SR we should maybe also switch the flye input parameter. 

Regarding the estimation of the error rate:
"Probably the most commonly used definition of read accuracy is the percentage of bases in a segment of a read that match with a reference relative to the length of the readsegment–reference alignment"
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1462-9

So it would be best if we could map the reads to a reference to estimate the error rate. I think what we could do is: mapping the raw and error-corrected LRs of one sample to the final assembly. The final assembly should be of high quality due to the SR polishing step. However, I would skip this for now because it takes time. However, also for the paper, later on, it would be good if we can state something about the error rates.
