### ISSUE TITLE
racon via conda

### ISSUE THREAD

**Issue by hoelzer** [sandraTriebel/mycoplasma_bovis_assembly#8]
is it possible to run racon via conda instead of a docker container?

**Comment by sandraTriebel** [comment]
Racon has a new version. We used 1.3.2 and 1.4.10 is available.
I'll try to install it via conda (https://anaconda.org/bioconda/racon), theoretically it should be possible.

**Comment by hoelzer** [comment]
Ok, great. Hopefully it is working and we can avoid the docker

**Comment by sandraTriebel** [comment]
We tried many ways to make racon work (conda, docker new and old). Only the old racon version via docker is going to work currently.
